### ISSUE TITLE
SQL File

### ISSUE THREAD

**Issue by fthtrnn** [KgaugeloEliasMatlou/Asset-Filer#1]
hey man,

I wanted to try the system you shared but I realized that there is no SQL file. if you have a SQL file, can you share it?

Kind Regards,

**Comment by KgaugeloEliasMatlou** [comment]
[assets_management_db.zip](https://github.com/KgaugeloEliasMatlou/Asset-Filer/files/12418060/assets_management_db.zip)

import this dump into your mysql work bench 

change the credential according to your server

**Comment by fthtrnn** [comment]
![image](https://github.com/KgaugeloEliasMatlou/Asset-Filer/assets/142986703/d35be8fa-240b-46ec-9124-dae323f05bcc)
after upload this dumps to phpmyadmin yep login and some save /delete functions worked but every page same error "Warning: Undefined array key "savedbootstrapclass" any ideas of this error ?

**Comment by KgaugeloEliasMatlou** [comment]
This is a bootstrap class that changes colour of text wen u enter wrong inputs

on my local environment it works well

This dump is for MYSQL WORKBENCH NOT PHP MYADMIN

**Comment by fthtrnn** [comment]
hmm okey xamp vs mysql workbench (same port chaos :( )
lemme check after search some kbase articles maybe found extra soutions because mysql&xampp too many issues
